dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: 60a2556c-baab-4b05-8184-8f7e9ac90991
  app: api-carteira
