dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: "$SECURE_KEY"
  app: "$APP"
env:
  global:
  - secure: oasm0Ery7V5bldZLv6MedjF3PLR2D7BP97nZYj//NHrMm9ZfKq3eoDnT7v6tEhKZOvG/K0q87lh4COWYuP8AnoVCKYz7eh0yZQhP0UHM/VneOFXQBjlrL3vUanFVhNFYlzJtlYeZkHQUlvC8t9yOwdWQvf8svh/ora7+rDR/UBGU9OD4es2pbeDeTxbtouX5yCypTnHhcW3WQ9CKINfStdpH51Sd3vkU0hcKbHkaDfG2gitT7GC4neKOZ5Dkbh+SUWXSRqeFB6MdxWSRO0p65QMmqO4jV13Zt6LgwHBWqjFJwg0m3MdQsmsd+htIhATmfsE9Jx3lnFKnwVYilQTGogsV+hS607SZNoA7jAlqiWvz2FXQc/JYJ+meM3oTiYbSjUAMm6nhWxVNw53pgDhaJwlLP4w3nHJL46XRJhUpDmNAT6hNhR7SnV/kWMTBAD2LMo5FtqiCkm+R5r+fraZFw8N8v3CxQztqoQq+fbuelC0w3CO/drowIR53I9us0dzXAqpaMEStyk7FQnZkEuZ2JE5fTW+tq2IAxyfREF3K3jqAPVLht15aqjym++d9QdHmmoTkUHdSJOMYk13gMx+jYp/lvnFA6T7uzFPRsYIO/GEeJGEFfCGpyMNH623w3JTOrD8wQEX001YEcHYEyFz2aKiPWc41Euc6Q15oXYpuMfM=
  - secure: PQ4AEc8pAxmK+XT3zMNx0QkCePkDBXettm18YMnfO8bhzAz3NukMKTsb1R1zk4I0OnRsAQJptzuVssj7Q/QoB0oS95WaMi03ELGc1+5+UGefJmSeFoNKlAmXKzrKg7823qWCC0Y1+fNoEsLaYjZnhkZ146U6EP4UKAbt0PxrPrepZIIUgO4AuQAuVzvpsX8NeLFgzbfpJM6WKL1HgzVjHAhSt3qblLy0PeKHs9ZiUeUSo5inocgeWNouS1acLrnaigjMcASb6RO4GC6miWz2gwkzzr/WXQy3TEjOd4UGHqnx9G9I4S6Hlsuh9TuQ6Ni/n3tPZBRQzT8b+Fg+Oag0g5rnYGeDCMsykwRbT0pfrRruHuPfx81spJUpQUA89cT0kNPC2ZKpFpUwmVpkDPxWX0g59isqvCF4GUruJgLXJglWMCcK3l3Qf1vQkS6Frz4TnWnrFhqoOp58WY2c+LmapOhepBCO4wS6YU8As8Hef+fcYU8wJmw0rGjJMcuXTc8WS9zJ8/VeY2ZUc7vBwggGX0dytRxCUB+o0TQ+gk15LFnRQmmX8fVZmbcNOloscSEU2ep9Vd93oddyhPVYldataBHhMtlvyPVuxwZIhbXWJ2JpPfY8Dt80KKZmmQ8cgpXKgPPtBoeMki4TNWtsg0Kzkv5YBJui64bCbcQ7NpwmtoU=
